# Generated by Django 3.0.7 on 2020-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
