# Generated by Django 3.0.7 on 2020-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'WhiteList', 'verbose_name_plural': 'WhiteList'},
        ),
        migrations.AddField(
            model_name='whitelist',
            name='response_in_add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='response_in_remove',
            field=models.TextField(blank=True, null=True),
        ),
    ]
